services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
    ports:
      - 5432:5432
    restart: always
    volumes:
      - database:/var/lib/postgresql/data
  backend:
    build:
      context: packages/backend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - postgres
    restart: always

volumes:
  database:
